name: React frontend CI/CD with AWS S3

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Installing project dependencies and building the production build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4196"
          yarn install --frozen-lockfile
          yarn build

      - name: Upload production build to S3 bucket
        run: |
          aws s3 sync build ${{ vars.S3_BUCKET_URI }}
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'